In [10]:
from numpy import array
import numpy as np

a = array([1,2,3,4,5])

print type(a)
print a.dtype
print a.itemsize
print a.shape
print np.shape(a)
print a.size
print a.nbytes
print a.ndim

<type 'numpy.ndarray'>
int32
4
(5L,)
(5L,)
5
20
1


In [5]:
from numpy import array

a = array([1,2,3,4,5])
b = array([5,4,3,2,1])

print a+1
print a+b
print a*b
print a**b

[2 3 4 5 6]
[6 6 6 6 6]
[5 8 9 8 5]
[ 1 16 27 16  5]


In [9]:
print a[0]
print a[:2]
print a[-2:]

1
[1 2]
[4 5]


In [10]:
print a[:2]+a[-2:]

[5 7]


In [16]:
a = array([1,2,3,4])
a.shape

a.shape = 2,2
print a

print a+a
print a*a

[[1 2]
 [3 4]]
[[2 4]
 [6 8]]
[[ 1  4]
 [ 9 16]]
