In [4]:
import numpy as np

person_type = np.dtype({'names':['name','age','chinese','math','english'],
                        'formats':['S32','i','i','i','f']})

peoples = np.array([('zhangsan',32,75,100,90),("guanyu",24,85,96,88.5),("zhaoyun",28,85,92,96.5),("huangzong",29,65,92,90.5)],
                   dtype=person_type)

peoples[::]['name']

print 'mean chinese score',np.mean(peoples[:]['chinese'])

print 'mean math score',np.mean(peoples[:]['math'])

print 'mean english score',np.mean(peoples[:]['english'])

print peoples.dtype

mean chinese score 77.5
mean math score 95.0
mean english score 91.375
[('name', 'S32'), ('age', '<i4'), ('chinese', '<i4'), ('math', '<i4'), ('english', '<f4')]


## 算术运算

In [11]:
import numpy as np
# 1~11 范围内按照step生成元素
x1 = np.arange(1,11,2)
# 1~9 范围内，生成5个元素，包括终值
x2 = np.linspace(1,9,5)
print x1,x2

print np.add(x1,x2) , x1+x2
print np.subtract(x1,x2) , x1-x2
print np.multiply(x1,x2) , x1*x2
print np.divide(x1,x2) , x1/x2

print np.power(x1,x2) , x1**x2
# 求余,三种方式都可以
print np.remainder(x1,x2),np.mod(x1,x2), x1%x2

[1 3 5 7 9] [ 1.  3.  5.  7.  9.]
[  2.   6.  10.  14.  18.] [  2.   6.  10.  14.  18.]
[ 0.  0.  0.  0.  0.] [ 0.  0.  0.  0.  0.]
[  1.   9.  25.  49.  81.] [  1.   9.  25.  49.  81.]
[ 1.  1.  1.  1.  1.] [ 1.  1.  1.  1.  1.]
[  1.00000000e+00   2.70000000e+01   3.12500000e+03   8.23543000e+05
   3.87420489e+08] [  1.00000000e+00   2.70000000e+01   3.12500000e+03   8.23543000e+05
   3.87420489e+08]
[ 0.  0.  0.  0.  0.] [ 0.  0.  0.  0.  0.] [ 0.  0.  0.  0.  0.]


## 统计函数

In [17]:
import numpy as numpy

a = np.array([[1,2,3], [4,5,6], [7,8,9]])

# 矩阵中的最小值
print np.amin(a)
# axis = 0 ,
print np.amin(a,axis=0)
print np.amin(a,axis=1)

# 矩阵中的最大值
print np.amax(a)
# axis = 0 ,
print np.amax(a,axis=0)
print np.amax(a,axis=1)

1
[1 2 3]
[1 4 7]
9
[7 8 9]
[3 6 9]


In [20]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])


# 最大值和最小值的差
print np.ptp(a)

print np.ptp(a,0)
print np.ptp(a,1)

8
[6 6 6]
[2 2 2]


In [24]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])

# 计算矩阵的值的总和的百分之50，即平均值
print np.percentile(a,50)

print np.percentile(a,50,0)
print np.percentile(a,50,1)

5.0
[ 4.  5.  6.]
[ 2.  5.  8.]


In [30]:
a = np.array([[1,2,3], [4,5,5], [7,8,9]])

# 中位数,即中间的数
print np.median(a)

# 平均值
print np.mean(a)

a = np.array([1,2,3,4])
# 加权平均值
print np.average(a,weights=[1,1,2,1])

5.0
4.88888888889
2.6


In [32]:
a = np.array([1,2,3,4])
# 标准差
print np.std(a)
# 方差
print np.var(a)

1.11803398875
1.25


In [38]:
a = np.array([[4,3,2],[2,4,1]])

print a
print np.sort(a)
# 将多维数组扁平化在排序
print np.sort(a,axis=None)
print np.sort(a,axis=0)
print np.sort(a,axis=1)

[[4 3 2]
 [2 4 1]]
[[2 3 4]
 [1 2 4]]
[1 2 2 3 4 4]
[[2 3 1]
 [4 4 2]]
[[2 3 4]
 [1 2 4]]


## 练习：统计全班的成绩

In [65]:
import numpy as np

self_dtype = np.dtype({'names':('name','cn','en','math','total'),'formats':('S32','i','i','i','i')}) 

data = np.array(
    [
        ('zhangfei',66,65,30,0),
        ('guanyu',95,85,98,0),
        ('zhanyun',93,92,96,0),
        ('huangzong',90,88,77,0),
        ('dianwei',90,90,90,0),
    ],dtype=self_dtype
)

print data

[('zhangfei', 66, 65, 30, 0) ('guanyu', 95, 85, 98, 0)
 ('zhanyun', 93, 92, 96, 0) ('huangzong', 90, 88, 77, 0)
 ('dianwei', 90, 90, 90, 0)]


In [66]:
def show(clazz,data):    
    print '---{}---'.format(clazz)
    print 'min:', np.min(data)
    print 'max:', np.max(data)
    print 'mean:', np.mean(data)
    print 'var:', np.var(data)
    print 'std:', np.std(data)

    
show('语文',data[:]['cn'])
show('英语',data[:]['en'])
show('数学',data[:]['math'])

for col in data.dtype.names:
    if col != 'name':
        show(col,data[:][col])

---语文---
min: 66
max: 95
mean: 86.8
var: 111.76
std: 10.5716602291
---英语---
min: 65
max: 92
mean: 84.0
var: 95.6
std: 9.77752524926
---数学---
min: 30
max: 98
mean: 78.2
var: 634.56
std: 25.1904743901
---cn---
min: 66
max: 95
mean: 86.8
var: 111.76
std: 10.5716602291
---en---
min: 65
max: 92
mean: 84.0
var: 95.6
std: 9.77752524926
---math---
min: 30
max: 98
mean: 78.2
var: 634.56
std: 25.1904743901
---total---
min: 0
max: 0
mean: 0.0
var: 0.0
std: 0.0


In [67]:
print '---method 1'
data[:]['total'] = data[:]['cn']+data[:]['en']+data[:]['math']
t = np.sort(data,order='total')
print t[::][::-1]


print '---method 2'
# 使用python内置的排序函数
sorted(data,cmp=lambda x,y:cmp(x[1]+x[2]+x[3],y[1]+y[2]+y[3]),reverse=True)

---method 1
[('zhanyun', 93, 92, 96, 281) ('guanyu', 95, 85, 98, 278)
 ('dianwei', 90, 90, 90, 270) ('huangzong', 90, 88, 77, 255)
 ('zhangfei', 66, 65, 30, 161)]
---method 2


[('zhanyun', 93, 92, 96, 281),
 ('guanyu', 95, 85, 98, 278),
 ('dianwei', 90, 90, 90, 270),
 ('huangzong', 90, 88, 77, 255),
 ('zhangfei', 66, 65, 30, 161)]